### PR TITLE
Use com.twitter.finagle.Service as base type for services

### PR DESCRIPTION
**Pull request by csakoda**

### CODE REVIEW

**Comment by csakoda** [comment]
@derekslager @greglook

**Review by greglook — APPROVED** [review]
LGTM :ship:

**Comment by derekslager** [comment]
What is the effect of this? Looks like possibly something that would be useful as an upstream patch?

**Comment by greglook** [comment]
The code was providing the generated  Thrift interface to the `proxy` call, which means that the generated class has a parent of `java.lang.Object`. This resulted in the `ClassCastException` that @csakoda was seeing:

```
Caused by java.lang.ClassCastException
  amperity.source.service.proxy$java.lang.Object$SourceService$ServiceIface$d5009d79
  cannot be cast to com.twitter.finagle.Service
```

Using the base class of `Service` makes the proxied class operate the way that the Finagle code expects services to actually be constructed, extending the base class and implementing the generated interface.

**Pull request merged**
